# -*- coding: utf-8 -*-
"""Team Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tz_nnQmQfzQnVOdl_MULyYf43-RkgrI3
"""

!pip install faker
!pip install pandas
!pip install openpyxl

import pandas as pd
from faker import Faker
import csv

# Create a Faker instance
fake = Faker()
# Open a CSV file for writing
with open('teams.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    # Generate 1000 fake people
    for i in range(1000):
        # Generate a fake name and skill level
        name = fake.name()
        skill_level = fake.random_int(25, 95)
        # Write the data to the CSV file
        writer.writerow([name, skill_level])

# Read in the data from teams.csv
with open('teams.csv', 'r') as f:
    reader = csv.reader(f)
    data = list(reader)
# Create a list of tuples (name, skill_level) from the data
teams = [(row[0], row[1]) for row in data]
# Sort the teams by skill level, from highest to lowest
teams.sort(key=lambda x: x[1], reverse=True)
# Create a list of 5 empty lists to represent the 5 teams
team_lists = [[] for _ in range(4)]
# Iterate over the teams and evenly distribute them among the 5 lists
for i, team in enumerate(teams):
    team_lists[i % 4].append(team)
# Print out the teams
for i, team in enumerate(team_lists):
    print(f'Team {i+1}: {team}')

# Write the teams to teams_out.csv
with open('teams_out.csv', 'w') as f:
    writer = csv.writer(f)
    for i, team in enumerate(team_lists):
        writer.writerow([f'Team {i+1}'] + [t[0] for t in team])
teams = pd.read_csv('teams_out.csv').transpose()
teams.to_csv('teams_out_transpose.csv')